// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadReuseport returns the embedded CollectionSpec for reuseport.
func loadReuseport() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ReuseportBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load reuseport: %w", err)
	}

	return spec, err
}

// loadReuseportObjects loads reuseport and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*reuseportObjects
//	*reuseportPrograms
//	*reuseportMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadReuseportObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadReuseport()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// reuseportSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportSpecs struct {
	reuseportProgramSpecs
	reuseportMapSpecs
	reuseportVariableSpecs
}

// reuseportProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportProgramSpecs struct {
	ReuseportBalanceProg *ebpf.ProgramSpec `ebpf:"reuseport_balance_prog"`
}

// reuseportMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportMapSpecs struct {
	SocketMap *ebpf.MapSpec `ebpf:"socket_map"`
}

// reuseportVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type reuseportVariableSpecs struct {
	NumSockets *ebpf.VariableSpec `ebpf:"num_sockets"`
}

// reuseportObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportObjects struct {
	reuseportPrograms
	reuseportMaps
	reuseportVariables
}

func (o *reuseportObjects) Close() error {
	return _ReuseportClose(
		&o.reuseportPrograms,
		&o.reuseportMaps,
	)
}

// reuseportMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportMaps struct {
	SocketMap *ebpf.Map `ebpf:"socket_map"`
}

func (m *reuseportMaps) Close() error {
	return _ReuseportClose(
		m.SocketMap,
	)
}

// reuseportVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportVariables struct {
	NumSockets *ebpf.Variable `ebpf:"num_sockets"`
}

// reuseportPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadReuseportObjects or ebpf.CollectionSpec.LoadAndAssign.
type reuseportPrograms struct {
	ReuseportBalanceProg *ebpf.Program `ebpf:"reuseport_balance_prog"`
}

func (p *reuseportPrograms) Close() error {
	return _ReuseportClose(
		p.ReuseportBalanceProg,
	)
}

func _ReuseportClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed reuseport_bpfeb.o
var _ReuseportBytes []byte
